version: '2'
services:
  mosquitto:
    image: docker pull eclipse-mosquitto:1.4.12
    stdin_open: true
    volumes:
    - mosquitto.conf:/mosquitto/config/mosquitto.conf
    - /mosquitto/data
    - /mosquitto/log
    tty: true
    ports:
    - 1883:1883/tcp
    - 9001:9001/tcp
    labels:
      io.rancher.container.pull_image: always