version: '2'
services:
  mariadb:
    scale: 1
    start_on_create: true
  appdaemon:
    scale: 1
    start_on_create: true
  rtl2mqtt:
    scale: 1
    start_on_create: true
  home-assistant:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
