name: Honeywell2mqtt
description: |
  For use with a software defined radio tuned that is tuned listen for Honeywell RF security sensors
version: "0.1.0"
category: Automation
maintainer: Chris Kacerguis
license: Apache 2.0
projectURL: http://cowdog.io