name: Honeywell2mqtt
description: |
  For use with a software defined radio tuned that is tuned listen for Honeywell RF security sensors
version: "1.0.0"
category: Automation
maintainer: Chris Kacerguis
license: MIT
projectURL: http://cowdog.io