name: HADashboard
description: |
  HADashboard is a dashboard for Home Assistant that is intended to be wall mounted, and is optimized for distance viewing.
version: "2.0.0"
category: Automation
maintainer: Chris Kacerguis
license: Apache 2.0
projectURL: http://appdaemon.readthedocs.io/en/latest/DASHBOARD/