version: '2'
catalog:
  name: "RabbitMQ + MQTT"
  version: "3.6"
  description: "Open source message broker with MQTT and admin panel add-ons"
services:
  rabbitmq-mqtt:
    scale: 1
    start_on_create: true